global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'url-shortener-write'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['url-shortener-write:8081']

  - job_name: 'url-shortener-read'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['url-shortener-read:8082']